development:
  sessions:
    default:
      database: openshift_broker_dev
      hosts:
        - localhost:27017
      username: openshift
      password: mooo
  options:
    raise_not_found_error: false
    ssl: false
production:
  sessions:
    default:
      database: openshift_broker_dev
      hosts:
        - localhost:27017
      username: openshift
      password: mooo
  options:
    raise_not_found_error: false
    ssl: false
test:
  sessions:
    default:
      database: openshift_broker_dev
      hosts:
        - localhost:27017
      username: openshift
      password: mooo
  options:
    raise_not_found_error: false
    ssl: false
